### ISSUE TITLE
StackOverflowError on parsing huge json

### ISSUE THREAD

**Issue by Holmyara** [playframework/playframework#3855]
I've seen that similar issues have been closed as fixed but I'm getting StackOverflowError when I'm parsing huge json document (zipped size - 1GB, unzipped - 7.2 GB):

```
java.lang.StackOverflowError: null
	at play.extras.iteratees.ArrayCharString.$plus$plus(CharString.scala:143) ~[iteratees-extras_2.11-1.4.0.jar:1.4.0]
	at play.extras.iteratees.JsonParser$$anonfun$play$extras$iteratees$JsonParser$$stringContents$1$1.apply(Json.scala:450) ~[iteratees-extras_2.11-1.4.0.jar:1.4.0]
	at play.extras.iteratees.JsonParser$$anonfun$play$extras$iteratees$JsonParser$$stringContents$1$1.apply(Json.scala:414) ~[iteratees-extras_2.11-1.4.0.jar:1.4.0]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$16.apply(Iteratee.scala:503) ~[play-iteratees_2.11-2.3.6.jar:2.3.6]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$16.apply(Iteratee.scala:503) ~[play-iteratees_2.11-2.3.6.jar:2.3.6]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$16.apply(Iteratee.scala:503) ~[play-iteratees_2.11-2.3.6.jar:2.3.6]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$16.apply(Iteratee.scala:503) ~[play-iteratees_2.11-2.3.6.jar:2.3.6]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$16.apply(Iteratee.scala:503) ~[play-iteratees_2.11-2.3.6.jar:2.3.6]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$16.apply(Iteratee.scala:503) ~[play-iteratees_2.11-2.3.6.jar:2.3.6]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$16.apply(Iteratee.scala:503) ~[play-iteratees_2.11-2.3.6.jar:2.3.6]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$16.apply(Iteratee.scala:503) ~[play-iteratees_2.11-2.3.6.jar:2.3.6]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$16.apply(Iteratee.scala:503) ~[play-iteratees_2.11-2.3.6.jar:2.3.6]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$16.apply(Iteratee.scala:503) ~[play-iteratees_2.11-2.3.6.jar:2.3.6]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$16.apply(Iteratee.scala:503) ~[play-iteratees_2.11-2.3.6.jar:2.3.6]
```

**Comment by jroper** [comment]
This seems to be the `k` function recursively invoking itself, every time the iteratee is flatMapped, a new `k` function is passed to `Cont` which invokes the earlier `k` function.  It seems to be exactly the same problem that we had with `Future.flatMap`, and could probably be solved in the same way.  @richdougherty?

We don't usually encounter this issue because we mostly don't actually parse the stream, hence there's not a lot of flatMapping going on.  But the json iteratee is a parser combinator style iteratee, where there's a lot of recursive flatMapping, after each token, field name, value, etc, there's always an Iteratee.flatMap.

**Comment by richdougherty** [comment]
@jroper I think you're right. I'll take a look and see if I can make a test that reproduces the issue.

**Comment by richdougherty** [comment]
It is closely related to the Future.flatMap problem (which was a memory leak not a stack overflow). The Future.flatMap problem had onComplete chains linking the Future objects together. This could grow in an unbounded way. We could eliminate the leak by flattening the chains.

There's unbounded function composition happening in Iteratee.flatMap. This could eventually cause a memory leak because of the huge chain of closures all pointing back to each other. It can definitely cause stack overflows when called, as you've seen.

It's easier to see if we rewrite the closure inside flatMap as a named function.

```scala
def fm(k, f, ec) = i => k(i).flatMap(f)(ec)
```

Once we've done this we can see the effect of repeated flatMap calls.
```scala
c1 = Cont(k1)

c2 = c1.flatMap(f2)(ec2)
c2 = Cont(k1).flatMap(f2)(ec2)
c2 = Cont(fm(k1, f2, ec2))
c2 = Cont(k2) where k2 = fm(k1, f2, ec2)

c3 = c2.flatMap(f3)(ec3)
c3 = Cont(k2).flatMap(f3)(ec3)
c3 = Cont(fm(k2, f3, ec3))
c3 = Cont(fm(fm(k1, f2, ec2), f3, ec3))
c3 = Cont(k3) where k3 = fm(fm(k1, f2, ec2), f3, ec3)

c4 = c3.flatMap(f4, ec4)
... snip ...
c4 = Cont(k4) where k4 = fm(fm(fm(k1, f2, ec2), f3, ec3), f4, ec4)

c5 = c4.flatMap(f5, ec5)
... snip ...
c5 = Cont(k5) where k5 = fm(fm(fm(fm(k1, f2, ec2), f3, ec3), f4, ec4), f5, ec5)
```

At least that's the theory. :) I'll try to write a unit test now to see if I can get the error. Then I'll look at a solution. I don't think we can use the same solution as we used for Futures because in this case we don't have an internal structure of completion handlers we can work with. I'm certain we can get something to eliminate the recursion (e.g. a trampoline), but I'm not sure about how to avoid collecting all the parameters (k1, f2, ec2, f3, ec3, f4, ec4, f5, ec5, …) at each step. Maybe we can't avoid that.

**Comment by richdougherty** [comment]
I've written a fix for the StackOverflowError, see #3863. I believe the closure can in theory exhaust memory but I'm not sure what to do about this.

**Comment by pepite** [comment]
I still experience the stack overflow error with the fix. I ll try to have a demo project ready.

**Comment by richdougherty** [comment]
I'm pretty sure I fixed one StackOverflowError, because the unit test I added failed before the fix, but there could be more than one. A test project or even an indication of which method/closure is that has the recursion is would be helpful.

**Comment by craigtmc** [comment]
Can I get his fix applied to 2.3.x branch?  I am getting a StackOverflow using ReactiveMongo's bulkInsert with an Enumeratee.  I tracked it down to Iteratee.flatMap when I am using a custom ExecutionContext that returns a new EC from prepare.  I have confirmed that applying this change to the 2.3.x branch fixes the StackOverflow.

**Comment by richdougherty** [comment]
@craigtmc, is there any chance you could provide sample code or a sample project?
