### ISSUE TITLE
Memory leak when using Play + Mockito

### ISSUE THREAD

**Issue by benmccann** [playframework/playframework#5144]
To reproduce see:
https://github.com/benmccann/play-mockito-bug

I was able to track the problem down to being an issue with Play + Mockito, but am not quite sure how to debug from here

**Comment by benmccann** [comment]
I changed this to a regular SBT non-Play project and the memory leak went away, so there must be something Play-related causing problems here.

**Comment by jroper** [comment]
My guess - changing to a non Play project makes it go away because when it's a Play project that runs Play tests, you're loading many megabytes of classes just for one test, so you have to run `test` an order of magnitude more times to reproduce.

I guess Mockito is starting a thread or doing something bad with classloaders that keeps them hanging around.

This is easy to work around by setting:

    fork in Test := true

**Comment by benmccann** [comment]
Good thought, but I don't think it's that. Each unit test in the sample project (there are 100 copies of the test) loads a 1MB file into memory 10 times. So basically running `test` loads about 1GB into memory. I can only run it a few times before it crashes with an OOM. [The plain SBT version](https://github.com/benmccann/play-mockito-bug/tree/sbt-no-play) I ran over 50 times in a row and it didn't crash.

**Comment by benmccann** [comment]
I simplified the test project dramatically. It turns out you don't need Mockito, loading a big file into memory, or lots of tests.

All you need to do is create a new Play project, set `fork in Test := false`, and run `test` about a half dozen times.

While it is true that `fork in Test := true` can help work around the bug, I still tend to hit this in my real project even with that setting. I think the problem is that it stops garbage collection of some objects which is fine if you finish the test run and kill the JVM, but if your test suite is too large then it means you can't get through a single run of the tests. If I set that and also run each individual test in it's own process instead of each test group, that helps more, but also dramatically slows down our tests.

**Comment by jroper** [comment]
When you set fork in test to be false, do you still get `Metaspace` out of memory errors?  Note that metaspace out of memory errors are generally caused by completely different things to heap space out of memory errors.  The problem is usually (though not always) caused by threads hanging around, that keep reference to the classloader that runs the tests, meaning the classloader can't be garbage collected, meaning all the associated metaspace that is used to store class data can't be returned.

**Comment by benmccann** [comment]
Yes, this report is only for `fork in Test := false`. It's the easiest problem to reproduce, so I wanted to address it first. Also, I need to set `fork in Test := false` in order to take a heap dump or attach visualvm so if we can fix the tests such that they run with that setting it will help me figure out other problems.

**Comment by shkhln** [comment]
Two things going here:

1. A soft reference to test classloader is stored with each `ObjectStreamClass.lookup` call @ https://github.com/junit-team/junit4/blob/r4.12/src/main/java/org/junit/runner/Result.java#L27. Per [this](http://stackoverflow.com/a/20461446) Stackoverflow answer the expiration period can be adjusted by setting `-XX:SoftRefLRUPolicyMSPerMB` to 1 (default is 1000).

2. There is some other problem with PlayNettyServer (or Netty itself) preventing classloaders from being collected. PlayAkkaHttpServer is unaffected.

**Comment by shkhln** [comment]
> There is some other problem with PlayNettyServer (or Netty itself)

Turns out, it's a jdk bug: https://bugs.openjdk.java.net/browse/JDK-8151486. ([Class.forName](https://github.com/netty/netty/blob/e7449b1ef361c55457ed21d44d6ed8387ec1fa45/common/src/main/java/io/netty/util/internal/PlatformDependent0.java#L223), [SecurityManager](https://github.com/sbt/sbt/blob/480a2f3040b8e13bd0606a5324d7b8cc60af519a/main/src/main/scala/sbt/Main.scala#L76)).

**Comment by marcospereira** [comment]
I was not able to reproduce this exact problem with Play 2.5.12. But I found a problem when using Logback async appenders. Apparently, there is a thread leak with daemon threads regarding those appenders. Here is a thread dump:

https://gist.github.com/marcospereira/46bede45c797955d57bd60d4bd9a93ed

We are already [stopping logback as suggested in theirs docs](https://logback.qos.ch/manual/configuration.html#stopContext):

https://github.com/playframework/playframework/blob/2.5.12/framework/src/play-logback/src/main/scala/play.api.libs.logback/LogbackLoggerConfigurator.scala#L103-L112

This could be related to one of these Logback issues:

1. https://jira.qos.ch/browse/LOGBACK-872
2. https://jira.qos.ch/browse/LOGBACK-1170

But we should also investigate on our side.

**Comment by shkhln** [comment]
> I was not able to reproduce this exact problem with Play 2.5.12.
All you need is Monitor -> Metaspace diagram in VisualVM.

**Comment by shkhln** [comment]
> play.runsupport.Reloader

That's for `run` command, actually. For `test` command this should something like sbt.classpath.*Loader.

**Comment by marcospereira** [comment]
Can you confirm this is happening for both Java and Scala projects?

**Comment by shkhln** [comment]
JDK-8151486 is applicable to both type of projects, but it is fixed in openjdk 9 and it is quite easy to disable sbt security manager (`trapExit := false`) as a workaround. There is nothing to be done here.

Soft reference issue is every bit as general as thread leaks and can sneak in any kind of sbt project. In this instance it is cased by Junit 4. Version 5 doesn't use ObjectStreamClass anywhere.

**Comment by shkhln** [comment]
> easy to disable sbt security manager (`trapExit := false`) as a workaround

Sorry, that setting doesn't do what I thought it does. Place `initialize := { System.setSecurityManager(null) }` in build.sbt instead.

**Comment by dwickern** [comment]
I just published https://github.com/dwickern/sbt-classloader-leak-prevention after struggling with these problems myself.

**Comment by wsargent** [comment]
Okay -- so, what's the action for Play?  Update all the example projects, include the sbt plugin?  It does seem like this is an SBT bug -- the Netty bug will be less of a problem in 2.6 as we are moving to Akka HTTP as the underlying engine.

**Comment by shkhln** [comment]
> Soft reference problem is every bit as general as thread leaks and can sneak into any kind of sbt project.

I'd like to backtrack on that statement a bit. With this sample project, the first time I'm out of metaspace, jvm consistently manages to collect softrefs and throw oom exception at the same time. It doesn't crash sbt, so I can run it again and again, and sofref gc mostly works ok, producing oom exceptions only occasionally. Likely another openjdk bug.

**Comment by jeantil** [comment]
>It does seem like this is an SBT bug 
@wsargent  actually it could very well be  http://github.com/sbt/sbt/issues/2496 which seems to point to a JDK bug...

Couldn't it be the source of these problems? 

Unfortunately @fommil's solution of using https://github.com/fommil/class-monkey isn't compatible with playframewor's classloader manipulation and yields [errors on run](https://github.com/fommil/class-monkey/issues/26) but my knowledge of runsupport is way too lacking for me to help diagnose :(

**Comment by NovaMage** [comment]
This issue is still around in play framework 2.6.12.  To reproduce in the simplest way, just create a test that instantiates a single instance of any of the selenium drivers (I tested with ChromeDriver, FirefoxDriver and HTMLUnitDriver) and then just quit the driver.  Even doing just this leads to a leak after running the test about a dozen times with default JVM memory settings on ubuntu.

I'm using sbt 1.0, scala 2.12.4, scalatestplus-play 3.1.2.

**Comment by NovaMage** [comment]
Actually, just tested this in a project that doesn't use play and the leak still happens.  Take https://github.com/NovaMage/SValidator and set `fork in Test := false`.  Launch the sbt REPL and run `test` a bunch times.  Shouldn't take long before an `OutOfMemoryError: Metaspace` occurs.

So I guess the leak is either in ScalaTest or sbt (or a combination of both)

**Comment by mkurz** [comment]
FYI: JDK-8151486 was fixed in OpenJDK 8u232 as well (not just JDK 9+):
* https://github.com/openjdk/jdk8u/commit/9b1e583a41f53b36f037f62e297b4adb52ea0a66
* https://mail.openjdk.java.net/pipermail/jdk8u-dev/2019-October/010452.html

**Comment by mkurz** [comment]
Just a note: Make sure in tests you call `LoggerConfigurator(classloader).shutdown()` when you stop an app. See #10939
