### ISSUE TITLE
[2.4.6] CSRF doesn't work with compile-time dependency?

### ISSUE THREAD

**Issue by brikis98** [playframework/playframework#5517]
I'm on Play 2.4.6 and am trying to use [compile-time dependency injection](https://www.playframework.com/documentation/2.4.x/ScalaCompileTimeDependencyInjection):

```scala
class MyApplicationLoader extends ApplicationLoader {
  def load(context: Context) = {
    new MyComponents(context).application
  }
}

class MyComponents(context: Context) extends BuiltInComponentsFromContext(context) with GzipFilterComponents with CSRFComponents {
  override lazy val httpFilters: Seq[EssentialFilter] = Seq(gzipFilter, csrfFilter)
}
```

I'm also following the [CSRF docs](https://playframework.com/documentation/2.4.x/ScalaCsrf) to try to include a CSRF form field:

```html
@()(implicit request: RequestHeader)

@helper.form(routes.Application.create) {
  @helper.CSRF.formField
  <!-- some other form elements -->
}
```

At runtime, when I try to load the page that has this form, I get the following exception:

```
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[InstantiationException: play.filters.csrf.CSRFConfig]]
  at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:265) ~[play_2.11-2.4.6.jar:2.4.6]
  at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[play_2.11-2.4.6.jar:2.4.6]
  at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:151) [play-netty-server_2.11-2.4.6.jar:2.4.6]
  at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:148) [play-netty-server_2.11-2.4.6.jar:2.4.6]
  at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) [scala-library-2.11.6.jar:na]
  at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:215) [scala-library-2.11.6.jar:na]
  at scala.util.Try$.apply(Try.scala:191) [scala-library-2.11.6.jar:na]
  at scala.util.Failure.recover(Try.scala:215) [scala-library-2.11.6.jar:na]
  at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) [scala-library-2.11.6.jar:na]
  at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) [scala-library-2.11.6.jar:na]
Caused by: java.lang.InstantiationException: play.filters.csrf.CSRFConfig
  at java.lang.Class.newInstance(Class.java:427) ~[na:1.8.0_66]
  at play.api.inject.NewInstanceInjector$.instanceOf(Injector.scala:49) ~[play_2.11-2.4.6.jar:2.4.6]
  at play.api.inject.SimpleInjector$$anonfun$instanceOf$1.apply(Injector.scala:85) ~[play_2.11-2.4.6.jar:2.4.6]
  at scala.collection.MapLike$class.getOrElse(MapLike.scala:128) ~[scala-library-2.11.6.jar:na]
  at scala.collection.AbstractMap.getOrElse(Map.scala:59) ~[scala-library-2.11.6.jar:na]
  at play.api.inject.SimpleInjector.instanceOf(Injector.scala:85) ~[play_2.11-2.4.6.jar:2.4.6]
  at play.api.inject.SimpleInjector.instanceOf(Injector.scala:80) ~[play_2.11-2.4.6.jar:2.4.6]
  at play.filters.csrf.CSRFConfig$$anonfun$global$1.apply(csrf.scala:63) ~[filters-helpers_2.11-2.4.6.jar:2.4.6]
  at play.filters.csrf.CSRFConfig$$anonfun$global$1.apply(csrf.scala:63) ~[filters-helpers_2.11-2.4.6.jar:2.4.6]
  at scala.Option.map(Option.scala:146) ~[scala-library-2.11.6.jar:na]
Caused by: java.lang.NoSuchMethodException: play.filters.csrf.CSRFConfig.<init>()
  at java.lang.Class.getConstructor0(Class.java:3082) ~[na:1.8.0_66]
  at java.lang.Class.newInstance(Class.java:412) ~[na:1.8.0_66]
  at play.api.inject.NewInstanceInjector$.instanceOf(Injector.scala:49) ~[play_2.11-2.4.6.jar:2.4.6]
  at play.api.inject.SimpleInjector$$anonfun$instanceOf$1.apply(Injector.scala:85) ~[play_2.11-2.4.6.jar:2.4.6]
  at scala.collection.MapLike$class.getOrElse(MapLike.scala:128) ~[scala-library-2.11.6.jar:na]
  at scala.collection.AbstractMap.getOrElse(Map.scala:59) ~[scala-library-2.11.6.jar:na]
  at play.api.inject.SimpleInjector.instanceOf(Injector.scala:85) ~[play_2.11-2.4.6.jar:2.4.6]
  at play.api.inject.SimpleInjector.instanceOf(Injector.scala:80) ~[play_2.11-2.4.6.jar:2.4.6]
  at play.filters.csrf.CSRFConfig$$anonfun$global$1.apply(csrf.scala:63) ~[filters-helpers_2.11-2.4.6.jar:2.4.6]
  at play.filters.csrf.CSRFConfig$$anonfun$global$1.apply(csrf.scala:63) ~[filters-helpers_2.11-2.4.6.jar:2.4.6]
```

Is CSRF still trying to do runtime dependency injection? Was that not fixed in #5368 by @mchv?

**Comment by brikis98** [comment]
Ah, I think the issue is that the `CSRF.formField` helper is [hard-coded to use global config](https://github.com/playframework/playframework/blob/26a9c7625d6c482abf1c6ecedacff34d670bee01/framework/src/play-filters-helpers/src/main/scala/views/html/helper/CSRF.scala):

```scala
  def formField(implicit token: play.filters.csrf.CSRF.Token): Html = {
    // probably not possible for an attacker to XSS with a CSRF token, but just to be on the safe side...
    Html(s"""<input type="hidden" name="${play.filters.csrf.CSRFConfig.global.tokenName}" value="${HtmlFormat.escape(token.value)}"/>""")
  }
```

**Comment by mchv** [comment]
@brikis98 good catch, look to how [we implemented it on our side](https://github.com/guardian/bonobo/blob/0a2a2213d1bf01612a8591f3e8e4e69f639e922d/app/controllers/csrf/CSRFSupport.scala)

**Comment by brikis98** [comment]
@mchv: Thanks. I built a similar workaround.

**Comment by schmitch** [comment]
You could also just change your template implicit.
That is what I did:

    // Hemplate Header:
    @(guestbookForm: Form[GuestbookForm])(implicit messages: Messages, token: play.filters.csrf.CSRF.Token)
    // Controller:
    def createView = Action { implicit r =>
    Ok(views.html.guestbook.create(GuestbookData.form))
    }

**Comment by brikis98** [comment]
@schmitch: Thanks, but even if I use an `implicit` token, I still get an exception with the `CSRF.formField` helper, probably because it looks up the `tokenName` in global config.

**Comment by schmitch** [comment]
@brikis98 did you also have a implicit request => inside your controller?

**Comment by gmethvin** [comment]
@brikis98 Yes, you're right. Play is trying to get the CSRFConfig from the runtime injector of the global application.

As a workaround you can override the `injector` in `BuiltInComponents`:
```scala
  lazy val csrfConfig: CSRFConfig = CSRFConfig()
  lazy val injector: Injector = new SimpleInjector(NewInstanceInjector) +
    router + crypto + httpConfiguration + tempFileCreator + global + csrfConfig
```

We definitely should change the API to avoid global state. Perhaps it'd be best to change to move the helper methods to an instance of `new CSRFHelper(csrfConfig, token)` or similar.

**Comment by richdougherty** [comment]
More discussion about a fix over here: https://github.com/playframework/playframework/pull/5526#issuecomment-177606867

**Comment by gmethvin** [comment]
@brikis98 An update on this issue:

This should be fixed in 2.5. Now we tag the request with the CSRF token so the helper can just extract the token from the tag. 

It may be possible to backport some of the changes, but since there are several workarounds it's not a priority right now.

**Comment by brikis98** [comment]
@gmethvin: Thanks for the update. The workarounds are straightforward, so it's no big deal to wait for 2.5. Thanks!

**Comment by marcospereira** [comment]
@gmethvin I think we can close this issue, right?
