### ISSUE TITLE
[2.6.11] AkkaHttpServer cannot cope with custom request handler

### ISSUE THREAD

**Issue by el-dom** [playframework/playframework#8181]
### Play Version (2.5.x / etc)
2.6.11

### API (Scala / Java / Neither / Both)
Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
Linux zbook 4.14.14-1-ARCH #1 SMP PREEMPT Fri Jan 19 18:42:04 UTC 2018 x86_64 GNU/Linux

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
```
openjdk version "1.8.0_144"
OpenJDK Runtime Environment (build 1.8.0_144-b01)
OpenJDK 64-Bit Server VM (build 25.144-b01, mixed mode)
```

I've followed the documentation for implementing a [custom request handler](https://www.playframework.com/documentation/2.6.x/ScalaHttpRequestHandlers#implementing-a-custom-request-handler) and activated it by adding it to the `application.conf` via `play.http.requestHandler = "my.package.FallbackRequestHandler"` 
At this point my code is identical with the example from the documentation

```scala
class FallbackRequestHandler @Inject()(router: Router) extends HttpRequestHandler {
  override def handlerForRequest(request: RequestHeader) =
    router.routes.lift(request) match {
      case Some(handler) => (request, handler)
      case None          => (request, Action(Results.NotFound))
    }
}
```
But every request ends in 

```
java.lang.RuntimeException: AkkaHttpServer doesn't handle Handlers of this type: play.api.mvc.Handler$Stage$$anon$1@4e55f437
	at scala.sys.package$.error(package.scala:27)
	at play.core.server.AkkaHttpServer.executeHandler(AkkaHttpServer.scala:268)
	at play.core.server.AkkaHttpServer.handleRequest(AkkaHttpServer.scala:200)
	at play.core.server.AkkaHttpServer.$anonfun$createServerBinding$1(AkkaHttpServer.scala:106)
	at akka.stream.impl.fusing.MapAsync$$anon$24.onPush(Ops.scala:1191)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:512)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:475)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:371)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:584)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:468)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:559)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:741)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:756)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:666)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
	at akka.actor.ActorCell.invoke(ActorCell.scala:496)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```
When driving requests through the custom handler, the `Handler` object doesn't seem to be an `EssentialAction`, causing the `AkkaHttpServer` to reject the handler.

Is there any way to work around this?

**Comment by marcospereira** [comment]
Thank you, @el-dom.

I can confirm this is happening for both Akka HTTP and Netty servers. For Netty, the exception is:

```
java.lang.IllegalStateException: Netty server doesn't handle Handlers of this type: play.api.mvc.Handler$Stage$$anon$1@710f5aad
	at play.core.server.netty.PlayRequestHandler.handle(PlayRequestHandler.scala:157)
	at play.core.server.netty.PlayRequestHandler.channelRead(PlayRequestHandler.scala:178)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at com.typesafe.netty.http.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:129)
	at com.typesafe.netty.http.HttpStreamsServerHandler.channelRead(HttpStreamsServerHandler.java:96)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
```
A possible work around (didn't tested it) is to [extend the default `HttpRequestHandler`](https://www.playframework.com/documentation/2.6.x/ScalaHttpRequestHandlers#Extending-the-default-request-handler).

**Comment by richdougherty** [comment]
You're probably missing a piece of logic to handle a `Handler.Stage`. This line from DefaultHttpRequestHandler is probably needed in your custom request handler:

https://github.com/playframework/playframework/blob/73c2e04df0621965366c73580120359d1ec8e58b/framework/src/play/src/main/scala/play/api/http/HttpRequestHandler.scala#L157

You can seed the code it calls and the `Handler.Stage` here:

https://github.com/playframework/playframework/blob/73c2e04df0621965366c73580120359d1ec8e58b/framework/src/play/src/main/scala/play/api/mvc/Handler.scala#L19-L72

A `Handler.Stage` is a kind of "filter" that can rewrite `RequestHeader`s at the `Handler` stage of request processing.

**Comment by ikr0m** [comment]
Guys, is it safe to switch play 2.6.11 version? I'm concerning about this issue because I've custom request handler in my project. Now I'm using 2.6.10 and I have a problem with #8096. It's fixed in 2.6.11. Is it safe to switch from 2.6.10 to 2.6.11 if I use custom request handler?

**Comment by marcospereira** [comment]
Hi @ikr0m,

If you are already using a custom request handler with Play 2.6.10, it is safe to upgrade to 2.6.11. I suspect your custom request handler is extending from the default one, right?

**Comment by ikr0m** [comment]
Thanks for the answer.
Yes, my custom request handler extends from `DefaultHttpRequestHandler`.

**Comment by gmethvin** [comment]
I think the documentation just needs to be updated to use `Handler.applyStages(request, handler)` instead of `(request, handler)`.

**Comment by Ottunger** [comment]
Still the same issue here and I don't really undersand why.
I'm trying to create internal fallback routes

```java
public class RequestHandler implements HttpRequestHandler {
  private final Router router;
  private final JavaHandlerComponents handlerComponents;

  @Inject
  public RequestHandler(Router router, JavaHandlerComponents components) {
    this.router = router;
    this.handlerComponents = components;
  }

  public HandlerForRequest handlerForRequest(Http.RequestHeader request) {
    Handler handler = null;
    Matcher versionMatcher = URI_VERSION.matcher(request.uri());
    if(!versionMatcher.find()) {
      handler = router.route(request).orElse(EssentialAction.of(req -> Accumulator.done(Results.notFound())));
    } else {
      int triedVersion = Integer.parseInt(versionMatcher.group(1));
      while(triedVersion != 0 && handler == null) {
        handler = router.route(request).orElse(null);
        triedVersion--;
        RequestHeader scalaRequest = request.asScala();
        request = scalaRequest.withTarget(scalaRequest.target().withUriString(request.uri().replaceAll(URI_PATTERN, String
            .valueOf(triedVersion)))).asJava();
      }
      if(handler == null) {
        handler = EssentialAction.of(req -> Accumulator.done(Results.notFound()));
      }
    }
    if (handler instanceof JavaHandler) {
      handler = ((JavaHandler)handler).withComponents(handlerComponents);
    }
    return new HandlerForRequest(request, handler);
  }
}
```

If anyoen has a clue I would be really glad

**Comment by marcospereira** [comment]
Hi @Ottunger,

The problem, as @gmethvin explained above, is that you can't directly use `router.route(request)` without calling `Handler.applyStages(request, handler)`. I didn't have time to try it in an application, but it should be something like:

```java
import play.api.mvc.Handler;
import play.api.mvc.Handler$;
import play.core.j.JavaHandler;
import play.core.j.JavaHandlerComponents;
import play.http.HandlerForRequest;
import play.http.HttpRequestHandler;
import play.libs.streams.Accumulator;
import play.mvc.EssentialAction;
import play.mvc.Http;
import play.mvc.Results;
import play.routing.Router;

import javax.inject.Inject;
import java.util.Optional;

class RequestHandler implements HttpRequestHandler {

    private final Router router;
    private final JavaHandlerComponents handlerComponents;

    @Inject
    public RequestHandler(Router router, JavaHandlerComponents components) {
        this.router = router;
        this.handlerComponents = components;
    }

    @Override
    public HandlerForRequest handlerForRequest(Http.RequestHeader request) {
        Handler handler = getHandlerForRequest(request).orElse(EssentialAction.of(req -> Accumulator.done(Results.notFound())));
        
        // Your custom logic here.
        
        if (handler instanceof JavaHandler) {
            handler = ((JavaHandler)handler).withComponents(handlerComponents);
        }
        return new HandlerForRequest(request, handler);
    }

    private Optional<Handler> getHandlerForRequest(Http.RequestHeader request) {
        return router
                .route(request)
                .map(handler ->
                    Handler$.MODULE$
                        // This is the missing part
                        .applyStages(request.asScala(), handler)
                        ._2()
                );
    }

}
```
By the way, I just noticed that we need to improve both the API for `play.http.DefaultHttpRequestHandler` (to be easier to extends, like the Scala API) and also we need documentation on par with [what we have for Scala](https://www.playframework.com/documentation/2.6.x/ScalaHttpRequestHandlers).

**Comment by Ottunger** [comment]
Thanks for the help @marcospereira 
Now I get a little error saying
```
[error] application - Caught Server Error java.lang.RuntimeException: No CSRF token was generated for this request! Is the CSRF filter installed?: java.lang.RuntimeException: No CSRF token was generated for this request! Is the CSRF filter installed?
```
Does that mean doing so bypasses all filters?
Anyways althoug it seems to work better already (the error is deep down in the rendering of the view), applying _2() methods seems like magic to me and I would be glad to have a little mroe doc :)

**Comment by almothafar** [comment]
Thanks for the code @marcospereira, I got the same issue and fixed with your code.

**Comment by Ottunger** [comment]
@gmethvin @marcospereira 
Any chance to have a look on why filters don't get applied? Been scratching my head to figure out why but no luck so far.

**Comment by richdougherty** [comment]
Hi @Ottunger, take a look at the default implementation of `handleRequest`: https://github.com/playframework/playframework/blob/2.6.12/framework/src/play/src/main/scala/play/api/http/HttpRequestHandler.scala#L111. Your implementation will need to handle all of that (applying stages, `GET` fallback for `HEAD` requests, 404 errors, applying filters.

> By the way, I just noticed that we need to improve both the API for play.http.DefaultHttpRequestHandler (to be easier to extends, like the Scala API) and also we need documentation on par with what we have for Scala.

Agreed, although I suspect this will be something to do for Play 2.7.

**Comment by richdougherty** [comment]
I created an issue for HttpRequestHandler API improvements: #8278.
